# Generated by Django 5.2 on 2026-03-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('MVR', 'Maldivian Rufiyaa')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('MVR', 'Maldivian Rufiyaa')], default='USD', max_length=3),
        ),
    ]
