# Generated by Django 5.2 on 2026-03-12 07:32

from django.db import migrations
from datetime import time


def set_default_pickup_time(apps, schema_editor):
    """Set default pickup_time for existing quotes"""
    Quote = apps.get_model('api', 'Quote')
    Quote.objects.filter(pickup_time__isnull=True).update(pickup_time=time(9, 0))


def reverse_default_pickup_time(apps, schema_editor):
    """Reverse operation - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_operatorsubscription_speedboat_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_pickup_time, reverse_default_pickup_time),
    ]
