# Generated by Django 5.2 on 2026-03-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20260312_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
