# Generated by Django 5.2 on 2026-03-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_platformsettings_quote_commission_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
